### ISSUE TITLE
An easier way to initialize State fields?

### ISSUE THREAD

**Issue by dmitshur** [go-pipe/pipe#1]
The [pipe.State](http://godoc.org/gopkg.in/pipe.v2#State) struct has fields like Dir, Env, Timeout that one can set before executing the pipe.

Currently, it's easy to set Timeout via the CombinedOutputTimeout, DividedOutputTimeout, OutputTimeout and RunTimeout funcs. The other two are harder to set. I am aware of ChDir and SetEnvVar pipes, but it feels odd to use them to _initialize_ a pipe state.

I think it'd be great if "upgrading" from os/exec to pipe would be were easier. If you have something like,

``` Go
cmd := exec.Command("foo")
cmd.Dir = bar
out, err := cmd.Output()
```

The equivalent pipe (without resorting to using ChDir) would be:

``` Go
// This entire func is a copy of pipe.Output(), but with `s.Dir = dir` line added.
func outputInDir(p pipe.Pipe, dir string) ([]byte, error) {
    outb := &pipe.OutputBuffer{}
    s := pipe.NewState(outb, nil)
    s.Dir = dir
    err := p(s)
    if err == nil {
        err = s.RunTasks()
    }
    return outb.Bytes(), err
}

p := pipe.Exec("foo")
out, err := outputInDir(p, bar)
```

I feel like there's room for improvement for the pipe API. But I'm not sure what it would be exactly. I would want it to be as similar to os/exec as possible, but the best I can think of is something like:

``` Go
p := pipe.Exec("foo")
s := pipe.NewState()
s.Dir = bar
out, err := s.Output(p)

// Or,
p := pipe.Exec("foo")
out, err := pipe.OutputOptions(p, StateOptions{Dir: bar})
```

Primarily, I just wanted to ask what you think. Should I just give in and use pipe.ChDir to initialize the Dir? Or do you think something else can be done.

**Comment by dmitshur** [comment]
Ok, I ended up adding [pipe_util.OutputDir](https://github.com/shurcooL/go/blob/42a751136d73f85303675ac0112d6b4dfad403f9/pipe_util/dir.go) which I think is good enough for me to close this issue.

**Comment by dmitshur** [comment]
> Primarily, I just wanted to ask what you think. Should I just give in and use pipe.ChDir to initialize the Dir? Or do you think something else can be done.

Any thoughts on this?

**Comment by bmatsuo** [comment]
Sorry for necropost but I have some thoughts on this.

@shurcooL I think that pipe.ChDir may be the right way to go. Your gist would end up needing "Combined" and "Timeout" variants. At that point I think its fair to say it's a combinatorial explosion.

I feel the pain of this. However, I also have the problem where I would like the environment to be set in each state.

I think the right thing to do may be to have something conceptually similar to a ".bashrc" file. Command(s) which are evaluated before each pipe.Pipe being run.

Just my two cents. Here's an example showing the basic idea I have.

``` go
// this is inside the "gopkg.in/pipe.v2" package
package pipe

type RC struct {
    Init Pipe
}

func (rc *RC) Run(p Pipe) error {
    if rc.Init == nil {
        Run(p)
    }
    return Run(Script(rc.Init, p))
}

// ... also define methods RC.Output and RC.CombinedOutput
```

``` go
// a script that imports "gopkg.in/pipe.v2"
func main() {
    cwd, _ := os.Getwd()
    rc := pipe.NewRC(pipe.Script(
        pipe.ChDir("example"),
        pipe.SetEnvVar("GOPATH", cwd),
    ))

    p, err := rc.CombinedOutput(pipe.Exec("go", "test", "-cover"))
    if err != nil {
         log.Fatalf("test: %v\n%s", err, p)
    }
    p, err = rc.Run(pipe.Exec("go", "build"))
    if err != nil {
         log.Fatalf("test: %v\n%s", err, p)
    }
}
```

**Comment by niemeyer** [comment]
I'd encourage you to build support for such an rc file locally, but it seems beyond the scope of the pipe package itself.

@shurcooL I've read your post several times now in an attempt to extract what you're actually asking for, but I cannot come up with a reason why it's not a matter of just using pipe.ChDir?

**Comment by niemeyer** [comment]
I'm going to go ahead and close the issue on that basis, but please feel free to reopen if you feel I misunderstood something.

**Comment by dmitshur** [comment]
Closing this is ok.

What I was actually asking is in this part:

> I feel like there's room for improvement for the pipe API. But I'm not sure what it would be exactly. I would want it to be as similar to os/exec as possible, but the best I can think of is something like:
> 
> ``` Go
> p := pipe.Exec("foo")
> s := pipe.NewState()
> s.Dir = bar
> out, err := s.Output(p)
> 
> // Or,
> p := pipe.Exec("foo")
> out, err := pipe.OutputOptions(p, StateOptions{Dir: bar})
> ```
> 
> Primarily, I just wanted to ask what you think. **Should I just give in and use pipe.ChDir to initialize the Dir? Or do you think something else can be done.**

I take that the answer is "use pipe.ChDir to initialize the working directory."

The reason I didn't like it at that time is because it makes switching from exec package to pipe less natural.

**Comment by niemeyer** [comment]
Understood. The pipe package definitely has a different mental model than the exec package, for good reasons. So I think it's natural that we use a mechanism that is appropriate to the model of the pipe package itself, instead of attempting to mimic what the exec package does.

**Comment by dmitshur** [comment]
Just curious, can you elaborate in what ways the mental model is different? I'd like to understand better.

> I am aware of ChDir and SetEnvVar pipes, but it feels odd to use them to _initialize_ a pipe state.

Maybe it's not a big deal. But it still feels odd to me.

**Comment by niemeyer** [comment]
This is an example from the web page:

```
p := pipe.Line(
    pipe.Exec("df"),
    pipe.Filter(func(line []byte) bool {
        return bytes.HasSuffix(line, []byte(" /boot"))
    }),
    pipe.Tee(b),
    pipe.WriteFile("boot.txt", 0644),
)
```

That's how the pipe package models a pipeline, which can be further extended with any of the supported functions, or any other function you create. If you want to plug that pipeline into a different pipeline, it's trivial to do so. There's no "initialize a state" here.

**Comment by bmatsuo** [comment]
@niemeyer  thanks for the response.

FWIW it looks like the idea I threw out wouldn't quite work because wrapping things in a pipe.Script will prevent pipe.ChDir and pipe.SetEnvVar being observed in the pipe.Exec pipes.

**Comment by niemeyer** [comment]
ChDir should work nicely and easily within a Script. This test case is part of the test suite, for example:

```
 func (S) TestScriptIsolatesDir(c *C) {
        dir1 := c.MkDir()
        dir2 := c.MkDir()
        p := pipe.Script(
                pipe.ChDir(dir1),
                pipe.Script(
                        pipe.ChDir(dir2),
                ),
                pipe.System("echo $PWD"),
        )
        output, err := pipe.Output(p)
        c.Assert(err, IsNil)
        c.Assert(string(output), Equals, dir1+"\n")
}
```

**Comment by bmatsuo** [comment]
Right. The ChDir and SetEnv are observable inside the script. But the semantics I had envisioned in my "rc" example previously were more like this.

```
pipe.Script(
    pipe.Script(
        pipe.ChDir("example"),
        pipe.SetEnvVar("GOPATH", cwd),
    ),
    pipe.Exec("go", "test", "-cover"),
)
```

That is, I passed the NewRC function a pipe.Script in my example. I suppose making NewRC variadic would resolve that problem. But all I really meant was that **as written** it would not work.
