### ISSUE TITLE
Using channels, calling pipe.Output panics

### ISSUE THREAD

**Issue by mswift42** [go-pipe/pipe#2]
When I try to run this sample program: http://play.golang.org/p/J2rF9Ybg7B
It prints the correct output and then panics with: `panic: command "/usr/bin/find": exit status 1`. 

Am I doing something tremendously stupid, or is there a bug somewhere?

**Comment by niemeyer** [comment]
The panic comes from your own code (search for "panic" in it), and is caused by the "find" command (also in your code) returning a non-zero status.
