### ISSUE TITLE
Conditional logic

### ISSUE THREAD

**Issue by suntong** [go-pipe/pipe#3]
pipe is a fantastic gadget for go. Really powerful. 

I've been trying to think of a way to allow conditional source, but can't come up the idea myself. Basically what I need is exactly `sed` or `perl` etc are doing:
- if there is a file provided from the command line, then use it as the source
- else (no file provided from the command line), then use stdin as the source

I've read the doc several times, and have thought it over and over but can't come up a good idea myself (i.e., I think the conditional logic applying pipes are missing from the design). Can someone provide a sample code doing that please? 

PS. one more related question, 

If I have a complicated `Script`, which at the end there is a `RenameFile` operation:

```
    p := pipe.Script(
        pipe.Line(
            pipe.System(""),
            pipe.Exec("..."),
            pipe.Exec("..."),
        ),
        pipe.RenameFile("this", "that"),
    )
```

Is there any possibility not to do the `RenameFile` operation if any of the above command failed? I want to overwrite my file only if all is good.

Thanks

**Comment by dmitshur** [comment]
Conditional logic does sound counter to the notion of a pipeline. It should be just a sequence of steps, and it should cancel if any one of them fails, but more complex logic falls out of scope. But I know that it can be desirable to have some logic... Maybe the repo owner can give you a better answer.

I've used `pipe.TaskFunc` to do some custom things. Perhaps this is helpful. In my case, I was introspecting the contents that passed through the pipeline:

``` Go
pipe.TaskFunc(func(s *pipe.State) error {
    var b bytes.Buffer
    io.Copy(&b, s.Stdin) // should check error
    // ... do something with b.Bytes() ...
    io.Copy(s.Stdout, &b) // should check error
    return nil
}),
```

Perhaps that can be your input and you can conditionally read from various sources... But again, that might not be what pipes are made for. At least as far as I know, and I could be wrong.

**Comment by suntong** [comment]
I now agree with you.
